name: "CI/CD Pipeline"

on:
  workflow_dispatch:

  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"

  pull_request:

jobs:
  phplint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: "laravel"
          verboseMode: "true"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔨 Fix linting issues"
          skip_fetch: true
  eslint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ESLint
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔨 Fix linting issues"
          commit_user_name: "GitHub Actions"
          skip_fetch: true